### ISSUE TITLE
bug #1

### ISSUE THREAD

**Issue by gpl666** [MatteoBartoli03/generator_of_pattern#1]
Se chiedo di generare un elenco parziale di pattern non riesco a farlo in base ad un solo parametro, devo inserirli per forza entrambi, mentre se metto "x" (ammesso che sia effettivamente x quello da inserire per ignorare il parametro) crasha il programma (o forse esce, non so, è molto rapido a chiudersi)

**Comment by gpl666** [comment]
stesso problema sul pattern singolo casuale

**Comment by MatteoBartoli03** [comment]
Ha perfettamente ragione mi sono dimenticato di inserire le cose che deve fare  se è presente la x.
Ma una curiosità se metto la x nel n di quadratini totali come fa a capire di che grandezza deve generare i pattern? 
Inoltre se metto la x nel n di quadratini pieni dopo non diventa come l'operazione 1 dell'elenco iniziale? 
Potrei farlo lunedì perché stasera è domani sono via?

**Comment by gpl666** [comment]
mettendo la x nel n di quadratini totali dovrebbe dare tutti quelli che vanno dal numero di pieni a 32 quadtratini totali, ma in effetti forse si pianta dato che a 32 ci mette ore ad arrivarci, per quello dicevo di far generare un elenco completo che resti in un file, così non deve generarlo ogni volta..
se invece la x si mette nel numero di pieni non viene come il punto 1, perchè il punto 1 mi genera tutti i pattern fino al numero specificato: se per esempio imposto 7 mi dà anche i pattern da 6, da 5, da 4, da 3, ecc

**Comment by MatteoBartoli03** [comment]
ho impostato che invece che 32 il numero di caratteri è 32

**Comment by MatteoBartoli03** [comment]
ho impostato che il numero di caratteri invece che 32 è 5

**Comment by gpl666** [comment]
in che senso?

**Comment by gpl666** [comment]
le caselle devono poter arrivare a 32

**Comment by MatteoBartoli03** [comment]
Si certo intendo quando inserisco la x nel primo parametro (nei pattern
casuali o elenco parziale ) i pattern verranno generati di 5 caratteri

Il lun 18 giu 2018, 16:12 gpl666 <notifications@github.com> ha scritto:

**Comment by gpl666** [comment]
rilancio: prima chiedi il numero di caratteri pieni; se viene inserita la x chiedi il numero di caselle (quindi generi tutti i pattern con quel numero di caselle, ad esempio tutti i pattern da 7); se viene inserito un numero chiedi il numero minimo e massimo di caselle, e li generi entro quel range, con limite 3->32 come sempre, e poi si arrangia l'utente se ha chiesto troppo e vuole lasciare il PC acceso overnight, che dici?

**Comment by MatteoBartoli03** [comment]
Ma quest'operazione va fatta solo per l'elenco parziale o anche per il
random?

Il lun 18 giu 2018, 16:28 gpl666 <notifications@github.com> ha scritto:

**Comment by MatteoBartoli03** [comment]
A mio parere a più senso apportare le modifiche da lei proposte solo alla
sezione dell'elenco parziale mentre lasciare invariata la parte random

Il lun 18 giu 2018, 19:36 Matteo Bartoli <matteobartoli01@gmail.com> ha
scritto:

**Comment by MatteoBartoli03** [comment]
Appena me lo sa dire carico il tutto su github

Il lun 18 giu 2018, 20:03 Matteo Bartoli <matteobartoli01@gmail.com> ha
scritto:

**Comment by MatteoBartoli03** [comment]
Ho caricato su github la versione aggiornata potrebbe dirmi se va bene o no?
Grazie

Il lun 18 giu 2018, 20:04 Matteo Bartoli <matteobartoli01@gmail.com> ha
scritto:
