### ISSUE TITLE
issue #1

### ISSUE THREAD

**Issue by gpl666** [MatteoBartoli03/generator_of_pattern#2]
Se scelgo di generare un pattern casuale secondo parametri definiti, dopo mi chiede "cosa vuoi fare?" ma non mi dice in che senso nè che cosa posso inserire: dovrebbe chiedere qualcosa tipo "cosa vuoi fare? w - mostra il pattern successivo; s - mostra il pattern precedente; m - torna al menu principale"

**Comment by MatteoBartoli03** [comment]
Si certo
